export interface DocumentFile {
  name: string;          // Generated by LLM (without number prefix)
  path: string;          // Full path including number prefix
  description: string;   // Why this file exists
  content: string;       // The actual markdown content
  order: number;         // Used for numbering
  category: string;      // e.g., 'core', 'technical', etc.
  subcategory?: string;  // e.g., 'vision', 'architecture', etc.
}

export interface DocumentCategory {
  name: string;
  description: string;
  order: number;
  subcategories?: {
    [key: string]: {
      description: string;
      order: number;
    };
  };
}

export interface DocumentStructure {
  categories: {
    [key: string]: DocumentCategory;
  };
  files: DocumentFile[];
  metadata: {
    style: string;
    audience: string[];
    purpose: string;
    format: string;
    generatedAt: string;
    version: string;
    context: {
      projectType: string;
      technicalStack: string[];
    };
  };
}

export interface GeneratedDocument {
  structure: DocumentStructure;
  outputDirectory: string;
}
